<div class="container">
    <div class="links">
        <h3>Customer Support</h3>
        <ul>
            <li><a href="https://1-demo-2-0-5.the1umastory.com/customer/account/">Track Your Order</a></li>
            <li><a href="returns">Returns &amp; Exchanges</a></li>
            <li><a href="#">Store Locator</a></li>
        </ul>
    </div>
    <div class="links">
        <h3>Our Brands</h3>
        <ul>
            <li><a href="company-info">About Luma</a></li>
            <li><a href="community">Community</a></li>
            <li><a href="#">Shop Venia</a></li>
        </ul>
    </div>
    <div class="links">
        <h3>Follow @lumafitness</h3>
        <a href="https://www.twitter.com/lumafitness" target="_blank"><img src="https://m2-cdn.the1umastory.com/demo-2.0.5-ese1/media/wysiwyg/luma2-home/footer-twitter.jpg" alt=""></a>
    </div>
    <div class="links">
        <h3>Find A Store Near You</h3>
        <a href="/storelocator"><img src="https://m2-cdn.the1umastory.com/demo-2.0.5-ese1/media/wysiwyg/luma2-home/footer-store-search.jpg" alt=""></a>
    </div>
    <div class="links">
        <div class="newsletter">
            <h3>Newsletter</h3>
            <div class="block newsletter">
                <div class="title"><strong>Newsletter</strong></div>
                <div class="content">
                    <form class="form subscribe" novalidate="novalidate" action="https://1-demo-2-0-5.the1umastory.com/newsletter/subscriber/new/" method="post" id="newsletter-validate-detail">
                        <div class="field newsletter">
                            <label class="label" for="newsletter"><span>Sign Up for Our Newsletter:</span></label>
                            <div class="control">
                                <input name="email" type="email" id="newsletter" placeholder="Enter your email address" data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        <div class="actions">
                            <button class="action subscribe primary" title="Subscribe" type="submit">
                                <span>Subscribe</span></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="social">
            <h3>Social Links</h3>
            <a href="https://www.facebook.com/ebayluma"><img src="https://m2-cdn.the1umastory.com/demo-2.0.5-ese1/media/wysiwyg/luma2-home/facebook.png" alt=""></a>
            <a href="https://twitter.com/thelumastory"><img src="https://m2-cdn.the1umastory.com/demo-2.0.5-ese1/media/wysiwyg/luma2-home/twitter.png" alt=""></a>
            <a href="https://www.youtube.com/channel/UCMdGhsvA7obKMxg9ZppXuIA"><img src="https://m2-cdn.the1umastory.com/demo-2.0.5-ese1/media/wysiwyg/luma2-home/youtube.png" alt=""></a>
            <a href="https://www.pinterest.com/TheLUMAStory/"><img src="https://m2-cdn.the1umastory.com/demo-2.0.5-ese1/media/wysiwyg/luma2-home/pinterest.png" alt=""></a>
            <a href="https://instagram.com/ebay_luma/"><img src="https://m2-cdn.the1umastory.com/demo-2.0.5-ese1/media/wysiwyg/luma2-home/instagram.png" alt=""></a>
        </div>
    </div>
</div>

<a class="facebook" href="https://www.facebook.com/ebayluma"></a>
<a class="twitter" href="https://twitter.com/thelumastory"></a>
<a class="youtube" href="https://www.youtube.com/channel/UCMdGhsvA7obKMxg9ZppXuIA"></a>
<a class="pinterest" href="https://www.pinterest.com/TheLUMAStory/"></a>
<a class="instagram" href="https://instagram.com/ebay_luma/"></a>